version: 0.2


phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 237601488461.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=237601488461.dkr.ecr.us-east-1.amazonaws.com/myrepository
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t myrepository .
      - docker tag myrepository:latest 237601488461.dkr.ecr.us-east-1.amazonaws.com/myrepository:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 237601488461.dkr.ecr.us-east-1.amazonaws.com/myrepository:latest
      - echo Writing image definitions file...
      - printf '[{"name":"container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - target/dorotech_teste-1.0-SNAPSHOT.jar