server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

amazon:
  aws:
    accesskey:  ${access.key}
    secretkey:  ${secret.key}
  dynamodb:
    endpoint: http://dynamodb.us-east-1.amazonaws.com

  queue:
    product-creation: products-creation

  region: us-east-1



